services:
  - type: web
    name: ftw-realtime
    runtime: docker
    plan: starter
    region: oregon
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: ftw-realtime-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ftw-realtime-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: ftw-realtime-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ftw-realtime-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: ftw-realtime-db
          property: name
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PORT
        value: "10000"
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: ftw-realtime-db
    plan: starter
    region: oregon
    databaseName: ftw_realtime
