defmodule FtwRealtimeWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :ftw_realtime

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_ftw_realtime_key",
    signing_salt: "6gV4WrXS",
    same_site: "Lax"
  ]

  socket "/socket", FtwRealtimeWeb.UserSocket,
    websocket: [
      check_origin: [
        "https://fairtradeworker.com",
        "https://www.fairtradeworker.com",
        "https://fairtradeworker.vercel.app",
        "http://localhost:3000"
      ]
    ],
    longpoll: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve uploaded files from priv/static/uploads
  plug Plug.Static,
    at: "/uploads",
    from: {:ftw_realtime, "priv/static/uploads"},
    gzip: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ftw_realtime,
    gzip: not code_reloading?,
    only: FtwRealtimeWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug FtwRealtimeWeb.Plugs.SecurityHeaders
  plug FtwRealtimeWeb.Router
end
